source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ROSiOS-boost_Example', :exclusive => true do
  pod "ROSiOS-boost", :path => "../"
end

target 'ROSiOS-boost_Tests', :exclusive => true do
  pod "ROSiOS-boost", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
